# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

config.vm.box = "box-cutter/ubuntu1404-desktop"



config.vm.provider "virtualbox" do |vb|
# Display the VirtualBox GUI when booting the machine
vb.gui = true
# Customize the amount of memory on the VM:
vb.memory = "2048"
vb.name = "NewHanover-kmmehta-MayPar"
end
config.vm.provision "shell", inline: <<-SHELL
gsettings set org.gnome.desktop.screensaver lock-enabled false
sudo apt-get update
add-apt-repository ppa:webupd8team/java

apt-get update -qq
echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
apt-get install --yes oracle-java8-installer
yes "" | apt-get -f install

sudo apt-get install unzip

# tool download section

#sudo wget -O /home/vagrant/MayPar.zip "http://costa.ls.fi.upm.es/costabs/mhp/bin/MayPar_1.1_64.zip"
#unzip /home/vagrant/MayPar.zip -d /home/vagrant/MayPar
#cd /home/vagrant/MayPar/MayPar/bin
#chmod +x MayPar
#./MayPar main -i '../examples/DemoExample.abs' -v 3 -mode complete -l

# Creating Desktop files

sudo wget -O /home/vagrant/Desktop/desktop.zip "https://github.com/SoftwareEngineeringToolDemos/FSE-2012-MayPar/raw/master/build-vm/desktop.zip"
unzip /home/vagrant/Desktop/desktop.zip -d /home/vagrant/Desktop/
#sudo wget -O /home/vagrant/Desktop/desktop.tar.gz "https://github.com/SoftwareEngineeringToolDemos/FSE-2012-MayPar/raw/master/build-vm/desktop.tar.gz"
#mv desktop.tar.gz desktop.tar
#tar xvf /home/vagrant/Desktop/desktop.tar -C /home/vagrant/Desktop/
	sudo chmod a+x /home/vagrant/Desktop/*
	sudo chmod a+x /home/vagrant/Desktop/MayPar/*
	rm /home/vagrant/Desktop/desktop.zip
	
# Add tool as startup application
sudo mkdir "/home/vagrant/.config/autostart"
sudo mv /home/vagrant/Desktop/MayPar.desktop /home/vagrant/.config/autostart/
#sudo mv MayPar.desktop /home/vagrant/.config/autostart/MayPar.desktop
#sudo cp Desktop/MayPar.desktop /home/vagrant/.config/autostart/MayPar.desktop

# Remove unnecessary launcher applications
	sudo rm -f "/usr/share/applications/ubuntu-amazon-default.desktop"
	sudo rm -f "/usr/share/applications/libreoffice-calc.desktop"
	sudo rm -f "/usr/share/applications/libreoffice-writer.desktop"
	sudo rm -f "/usr/share/applications/libreoffice-impress.desktop"
	sudo rm -f "/usr/share/applications/ubuntu-software-center.desktop"

	# Disable screen lockout
	mv /home/vagrant/Desktop/login_desktop.sh /home/vagrant/login_desktop.sh
	sudo update-desktop-database
	sudo cp /home/vagrant/Desktop/login_desktop.sh.desktop /etc/xdg/autostart/login_desktop.sh.desktop
	rm /home/vagrant/Desktop/login_desktop.sh.desktop
	# Reboot the VM
	sudo reboot

SHELL
end
